### PR TITLE
Use annotations instead of channel names to identify bindings

### PR DESCRIPTION
**Pull request by mbogoevici**

### CODE REVIEW

**Comment by markfisher** [comment]
LGTM; merging

**Comment by markfisher** [comment]
I take that back. I have test failures with this. Lots of them, e.g.

````
twoOutputsWithQueue(org.springframework.cloud.streams.config.ChannelBindingAdapterConfigurationTests)  Time elapsed: 0.005 sec  <<< ERROR!
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'output' is defined
````

**Comment by mbogoevici** [comment]
Yeah, the naming thing is far too tangled with the test suite. I'll redo this.

**Comment by mbogoevici** [comment]
Reopened after internal refactoring and fixing tests. Removed 'source-xml' too.

**Comment by markfisher** [comment]
squashed and merged as https://github.com/spring-cloud/spring-cloud-streams/commit/a68321e8d5f0b607caf493cd3ded87392e972e12

**Pull request closed without merging**
